### PR TITLE
Added a .desktop file

### PR DESCRIPTION
**Pull request by denilsonsa**
This should show a desktop icon on your applications menu.

I've also improved the Makefile to make it easier to package this software in any distribution.

### CODE REVIEW

**Comment by denilsonsa** [comment]
Note: the `MimeType` entry let's it handle those image files (e.g. it will show up in the "Open with…" submenu of a filemanager).

However, this currently doesn't work, because this tool doesn't support any command-line arguments. It would be nice if you could add some basic `argv` parsing that would automatically load the file if it is passed as a parameter.

**Comment by vhelin** [comment]
> However, this currently doesn't work, because this tool doesn't support any command-line arguments. It would be nice if you could add some basic `argv` parsing that would automatically load the file if it is passed as a parameter.

I haven't touched this project for years, but I'll try to find time this weekend to try to do just that. Given that I can compile and run this on a modern Ubuntu distribution (have a mini PC with latest Ubuntu at home)...

**Comment by vhelin** [comment]
Also thanks for this PR!

**Comment by denilsonsa** [comment]
I understand you haven't touched it in years. :sweat_smile: (I've been neglecting my side projects for a long while now :disappointed: )

That's why I suggested a relatively small change that should be simple enough to implement: if there is at least one remaining argument in `argv` (after all the GTK processing and stuff), consider it a filename and try to load it (after the app has initialized.

Thanks for taking a look into this, very appreciated. I'm planning on submitting a `PKGBUILD` to [AUR](https://aur.archlinux.org/) sometime soon.

**Comment by vhelin** [comment]
> However, this currently doesn't work, because this tool doesn't support any command-line arguments. It would be nice if you could add some basic `argv` parsing that would automatically load the file if it is passed as a parameter.

I just added that command line argument -> load file -feature to the latest sources, but I don't think that .desktop file works in Ubuntu 22.04 so I cannot test it...

**Comment by denilsonsa** [comment]
Hmm… I didn't know which image to use, so I picked up a random PNG file I had on my disk. Here's the result of `tiledriller whichwayisup.png`:

image

And here's the result after going to File → Open to open the exact same image:

image

I'm assuming there is something else wrong with your latest commit.

**Comment by denilsonsa** [comment]
> but I don't think that .desktop file works in Ubuntu 22.04 so I cannot test it...

Just tested it on my Manjaro Linux. It works fine:

image

Remember to install it to `/usr/share/applications/`, and you probably need to update the MIME cache or something.

**Comment by vhelin** [comment]
Ah, my own testcase only had one tile in it! I'll fix this tomorrow, I
guess I made the wrong view to open that image...

**Comment by vhelin** [comment]
Ok, that is good news. I have no idea what updating MIME cache means
though... :)

**Comment by denilsonsa** [comment]
> I have no idea what updating MIME cache means though... :)

Probably something like this: https://wiki.archlinux.org/title/Desktop_entries#Update_database_of_desktop_entries
(or just restarting or logging out/in could also work)

**Comment by vhelin** [comment]
Had a super busy weekend, no time to test that MIME cache stuff (I'll do it
tomorrow), but I think I managed to fix the command line argument -> load
file issue...

**Comment by denilsonsa** [comment]
PKGBUILD [submitted](https://wiki.archlinux.org/title/AUR_submission_guidelines) to AUR: https://aur.archlinux.org/packages/tile-driller-git

If you're familiar with [Gentoo's ebuild](https://devmanual.gentoo.org/quickstart/) files, [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) files are similar.

**Comment by vhelin** [comment]
No idea what Gentoo's ebuilds are either, but sounds good. :)

**Pull request merged**
